import type { Candidate } from '../types/candidate';

export const candidates: Candidate[] = [
  {
    id: '1',
    firstName: 'Jan',
    lastName: 'Jansen',
    fullName: 'Jan Jansen',
    role: 'Frontend Developer',
    location: 'Amsterdam',
    stage: 'Telefonisch interview',
    vacancy: 'Senior Frontend Developer bij TechCorp B.V.',
    addedAt: '15-11-2024',
    tags: ['React', 'TypeScript', 'Senior'],
    avatarUrl: undefined
  },
  {
    id: '2',
    firstName: 'Maria',
    lastName: 'de Vries',
    fullName: 'Maria de Vries',
    role: 'Marketing Manager',
    location: 'Utrecht',
    stage: 'Gesolliciteerd',
    vacancy: 'Marketing Manager bij Marketing Solutions',
    addedAt: '14-11-2024',
    tags: ['Marketing', 'Strategie', 'Teamlead'],
    avatarUrl: undefined
  },
  {
    id: '3',
    firstName: 'Pieter',
    lastName: 'Bakker',
    fullName: 'Pieter Bakker',
    role: 'Data Analyst',
    location: 'Rotterdam',
    stage: 'Voorgesteld',
    vacancy: 'Data Analyst bij Data Insights',
    addedAt: '13-11-2024',
    tags: ['Python', 'SQL', 'Analytics'],
    avatarUrl: undefined
  },
  {
    id: '4',
    firstName: 'Lisa',
    lastName: 'Visser',
    fullName: 'Lisa Visser',
    role: 'HR Business Partner',
    location: 'Den Haag',
    stage: 'In afwachting CV',
    vacancy: 'HR Business Partner bij People First',
    addedAt: '12-11-2024',
    tags: ['HR', 'Recruitment', 'Advies'],
    avatarUrl: undefined
  },
  {
    id: '5',
    firstName: 'Mark',
    lastName: 'van Dijk',
    fullName: 'Mark van Dijk',
    role: 'Backend Developer',
    location: 'Eindhoven',
    stage: 'Geen gehoor',
    vacancy: 'Junior Backend Developer bij StartupHub',
    addedAt: '11-11-2024',
    tags: ['Node.js', 'MongoDB', 'Junior'],
    avatarUrl: undefined
  },
  {
    id: '6',
    firstName: 'Sarah',
    lastName: 'Mulder',
    fullName: 'Sarah Mulder',
    role: 'Sales Executive',
    location: 'Amsterdam',
    stage: 'Twijfel kandidaat',
    vacancy: 'Sales Executive bij SalesPro',
    addedAt: '10-11-2024',
    tags: ['Sales', 'B2B', 'Commercieel'],
    avatarUrl: undefined
  },
  {
    id: '7',
    firstName: 'Tom',
    lastName: 'de Boer',
    fullName: 'Tom de Boer',
    role: 'Senior Frontend Developer',
    location: 'Utrecht',
    stage: 'Telefonisch interview',
    vacancy: 'Senior Frontend Developer bij TechCorp B.V.',
    addedAt: '09-11-2024',
    tags: ['React', 'Vue', 'Senior', 'Teamlead'],
    avatarUrl: undefined
  },
  {
    id: '8',
    firstName: 'Emma',
    lastName: 'van der Meer',
    fullName: 'Emma van der Meer',
    role: 'Marketing Specialist',
    location: 'Rotterdam',
    stage: 'Afwijzen',
    vacancy: 'Marketing Manager bij Creative Agency',
    addedAt: '08-11-2024',
    tags: ['Social Media', 'Content', 'Junior'],
    avatarUrl: undefined
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'van Leeuwen',
    fullName: 'David van Leeuwen',
    role: 'Full Stack Developer',
    location: 'Amsterdam',
    stage: 'Gesolliciteerd',
    vacancy: 'Full Stack Developer bij Digital Solutions',
    addedAt: '16-11-2024',
    tags: ['JavaScript', 'Python', 'DevOps'],
    avatarUrl: undefined
  },
  {
    id: '10',
    firstName: 'Femke',
    lastName: 'Janssen',
    fullName: 'Femke Janssen',
    role: 'UX Designer',
    location: 'Den Haag',
    stage: 'In afwachting CV',
    vacancy: 'UX Designer bij Design Studio',
    addedAt: '17-11-2024',
    tags: ['UI/UX', 'Figma', 'Research'],
    avatarUrl: undefined
  },
  {
    id: '11',
    firstName: 'Kevin',
    lastName: 'de Wit',
    fullName: 'Kevin de Wit',
    role: 'DevOps Engineer',
    location: 'Utrecht',
    stage: 'Telefonisch interview',
    vacancy: 'DevOps Engineer bij CloudTech',
    addedAt: '18-11-2024',
    tags: ['AWS', 'Docker', 'Kubernetes'],
    avatarUrl: undefined
  },
  {
    id: '12',
    firstName: 'Laura',
    lastName: 'van den Berg',
    fullName: 'Laura van den Berg',
    role: 'Product Manager',
    location: 'Amsterdam',
    stage: 'Voorgesteld',
    vacancy: 'Product Manager bij Innovation Labs',
    addedAt: '19-11-2024',
    tags: ['Agile', 'Scrum', 'Strategy'],
    avatarUrl: undefined
  },
  {
    id: '13',
    firstName: 'Michael',
    lastName: 'Smit',
    fullName: 'Michael Smit',
    role: 'Backend Developer',
    location: 'Rotterdam',
    stage: 'Gesolliciteerd',
    vacancy: 'Senior Backend Developer bij FinTech',
    addedAt: '20-11-2024',
    tags: ['Java', 'Spring', 'Microservices'],
    avatarUrl: undefined
  },
  {
    id: '14',
    firstName: 'Judith',
    lastName: 'de Jong',
    fullName: 'Judith de Jong',
    role: 'Data Scientist',
    location: 'Eindhoven',
    stage: 'Twijfel kandidaat',
    vacancy: 'Data Scientist bij AI Startup',
    addedAt: '21-11-2024',
    tags: ['Machine Learning', 'Python', 'R'],
    avatarUrl: undefined
  },
  {
    id: '15',
    firstName: 'Robert',
    lastName: 'Koster',
    fullName: 'Robert Koster',
    role: 'Sales Manager',
    location: 'Den Haag',
    stage: 'Geen gehoor',
    vacancy: 'Sales Manager bij Business Solutions',
    addedAt: '22-11-2024',
    tags: ['Sales', 'Management', 'B2B'],
    avatarUrl: undefined
  },
  {
    id: '16',
    firstName: 'Nina',
    lastName: 'Bosch',
    fullName: 'Nina Bosch',
    role: 'Frontend Developer',
    location: 'Amsterdam',
    stage: 'Telefonisch interview',
    vacancy: 'Frontend Developer bij Web Agency',
    addedAt: '23-11-2024',
    tags: ['HTML', 'CSS', 'JavaScript', 'Junior'],
    avatarUrl: undefined
  },
  {
    id: '17',
    firstName: 'Daniel',
    lastName: 'Vink',
    fullName: 'Daniel Vink',
    role: 'Mobile Developer',
    location: 'Utrecht',
    stage: 'Gesolliciteerd',
    vacancy: 'Mobile Developer bij App Studio',
    addedAt: '24-11-2024',
    tags: ['React Native', 'iOS', 'Android'],
    avatarUrl: undefined
  },
  {
    id: '18',
    firstName: 'Sanne',
    lastName: 'Willems',
    fullName: 'Sanne Willems',
    role: 'HR Assistant',
    location: 'Rotterdam',
    stage: 'In afwachting CV',
    vacancy: 'HR Assistant bij Staffing Company',
    addedAt: '25-11-2024',
    tags: ['HR', 'Admin', 'Junior'],
    avatarUrl: undefined
  }
];
